import AppKit

/// Watches the system pasteboard (which has no change notification) by polling `changeCount`,
/// honours the nspasteboard.org privacy markers so password managers are never recorded, and
/// hands captured content to the store. Capture is cheap; the store does the heavy disk work.
@MainActor
public final class ClipboardMonitor {
    public static let bundleIdentifier = "com.havokentity.mactools.clipboard"

    /// nspasteboard.org markers + common vendor markers. Any of these means "do not record."
    private static let excludedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("Pasteboard generator type")
    ]

    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")

    public var isPaused = false

    private weak var store: ClipboardStore?
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    public init(store: ClipboardStore) {
        self.store = store
        lastChangeCount = pasteboard.changeCount
    }

    public func start(interval: TimeInterval = 0.5) {
        stop()
        let timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.tick()
            }
        }
        timer.tolerance = interval / 4
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !isPaused, let store else { return }

        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: Self.excludedTypes) else { return }

        // Skip our own paste-backs (we stamp the source type) to avoid loops/duplicates.
        if let source = pasteboard.string(forType: Self.sourceType), source == Self.bundleIdentifier {
            return
        }

        guard let captured = readPasteboard(types: types) else { return }

        Task { await store.record(captured) }
    }

    private func readPasteboard(types: Set<NSPasteboard.PasteboardType>) -> CapturedPasteboard? {
        var captured = CapturedPasteboard()

        if let front = NSWorkspace.shared.frontmostApplication {
            captured.sourceAppBundleID = front.bundleIdentifier
            captured.sourceAppName = front.localizedName
        }

        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            captured.filePaths = urls.map { $0.path }
        }

        if let pngData = pasteboard.data(forType: .png) {
            captured.imageData = pngData
            captured.imageIsPNG = true
        } else if types.contains(.tiff), let tiffData = pasteboard.data(forType: .tiff) {
            captured.imageData = tiffData
            captured.imageIsPNG = false
        }

        if let rtf = pasteboard.data(forType: .rtf) {
            captured.rtfData = rtf
        }
        if let html = pasteboard.data(forType: .html) {
            captured.htmlData = html
        }
        if let string = pasteboard.string(forType: .string) {
            captured.string = string
        }

        return captured.isEmpty ? nil : captured
    }
}
